#
# Jackie - OnePage Jekyll Theme
# Configuration File
#

# Information for compile
exclude: ["Gemfile", "README.md"]

# Sass configuration
sass:
  sass_dir: _scss

# Information for deploy
baseurl: "https://jackie-krohn.github.io"

# the base hostname & protocol for your site
url: "https://jackie-krohn.github.io"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Jacqueline Krohn
# Website language
lang: en-US
# Header Title
header-title: <strong>Jacqueline Krohn</strong>
# Header Tagline
headter-tagline: Data. Engineering. <strong>Exploration.</strong>

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Download CV
  url: https://jackie-krohn.github.io/data/Jacqueline_Krohn_Resume.pdf #CHANGE LINK

# # Secondary Buttons - ----- MIGHT WANT TO DELETE
# header-secondary-button:
#   title: Discover More
#   url: "https://jackie-krohn.github.io/portfolio.html"

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: jacquelinekrohn1@gmail.com

# Offer Banner Link
# Default link is a link to all Sera OnePage products
#banner-link: https://themeforest.net/collections/6069390-sera

####################################
######  Global Social Links   ######
####################################
youtube: "#"
pinterest: "#"
facebook: https://www.facebook.com/jackie.krohn.9/
twitter: "#"
google-plus: "#"
vimeo: "#"
linkedin: https://www.linkedin.com/in/jacqueline-krohn/
instagram: https://www.instagram.com/jackie_krohn/
github: https://github.com/jackie-krohn/
email: mailto:jacquelinekrohn1@gmail.com

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar-me.jpg
  author-name: Jacqueline Krohn
  author-tagline: Creator
  author-info: BS Mechanical Engineering, MS Business Analytics
  author-social-links:
    youtube: "#"
    linkedin: https://www.linkedin.com/in/jacqueline-krohn/
    pinterest: "#"
    facebook: https://www.facebook.com/jackie.krohn.9/
    linkedin: https://www.linkedin.com/in/jacqueline-krohn/
    instagram: https://www.instagram.com/jackie_krohn/
    github: https://github.com/jackie-krohn/
    email: mailto:jacquelinekrohn1@gmail.com

# Google Map JS api
#   key-api: YOUR_GOOGLE_MAP_API_KEY
#   map-text: Locate me
#   map-lat: 44.4267674
#   map-lng: 26.102538399999958

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
# mailchimp:
#   user-id: REPLACEME
#   list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Theme created by Ohkimur
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Welcome to Jackie's Portfolio
about-description: My name is Jacqueline (Jackie) Krohn. I'm an engineer and data enthusiast. I earned my bachelor degree in mechanical engineering with a minor in business from The University of Texas at Austin and went on to earn my master degree in business analytics at the University of Notre Dame. Learn more about the skills I developed in my education, career, and free time. Check out some subjects and experiences that are important to me. 

#####################################
#############  Features  ############
#####################################
features-title: Work Process
features-description: I take the following approach in my work and demonstrate this process in my portfolio.

#
# Features
#
features:
  # Feature
  - title: Evaluate
    description: I love to understand the full picture by taking time to investigate problems and find interesting data. 
    icon: pe-7s-search

  # Feature
  - title: Create
    description: Through data processing, application of statistical methods, computer aided modeling, machine learning, and many more learned skills, I create solutions to engineering and data-based questions
    icon: pe-7s-vector

  # Feature
  - title: Solve
    description: I utilize crisp visualizations to communicate thourough solutions fueled by my perfectionsim.
    icon: pe-7s-graph2

#####################################
############  Portfolio  ############
#####################################
portfolio-title: Portfolio
portfolio-description: Check out some of the different projects I've worked on or passions of mine. Use the filter below to find what you're looking for faster.

#
# Portfolio Grid
#
portfolio-categories:
  [Engineering, Data, Visualization, Machine Learning, Passions]
portfolio:
  # Portfolio Item
  - title: NBA Team <br> Dashboard
    categories: [Visualization, Passions, Group Work]
    image: img-nba.jpg
    url: "https://jackie-krohn.github.io/nba-dashboard.html"
    git: "https://jackie-krohn.github.io/nba-dashboard.html"

  # Portfolio Item
  - title: Children's Mercy <br> Patient Analysis
    categories: [Machine Learning, Group Work]
    image: img-med.jpeg
    url: "https://jackie-krohn.github.io/childrens-mercy-patient-care.html"
    git: "https://jackie-krohn.github.io/childrens-mercy-patient-care.html"
    
  # Portfolio Item
  - title: Deep Learning <br> Pnemonia <br> Diagnostics
    categories: [Machine Learning]
    image: img-pne.jpg
    url: "https://jackie-krohn.github.io/pnemonia-image-recognition.html"
    git: "https://github.com/jackie-krohn/pneumonia-diagnosis"

  # Portfolio Item
  - title: Airline Customer <br> Satisfaction
    categories: [Machine Learning, Group Work]
    image: img-air.jpeg
    url: "https://jackie-krohn.github.io/airline-satisfaction.html"
    git: "https://github.com/jackie-krohn/airline-satisfaction-ml"

  # Portfolio Item
  - title: Scraping <br> Financial Data
    categories: [Data]
    image: img-fin.jpeg
    url: "https://jackie-krohn.github.io/financial-data.html"
    git: "https://github.com/jackie-krohn/scraping-fin-data"

  # Portfolio Item
  - title: Transmission Line <br> Monitoring
    categories: [Engineering]
    image: img-tran.jpg
    url: "https://jackie-krohn.github.io/transmission-monitoring-design.html"
    git: "https://jackie-krohn.github.io/transmission-monitoring-design.html"



  # # Portfolio Item
  # - title: S<span class="thin">era</span> Style
  #   categories: [Photography, Logo]
  #   image: img-09.jpg
  #   url: "#"

#####################################
##########  Core Features  ##########
#####################################
core-title: Skills
core-description: I've developed the following skills through my projects and work experience. 

#
# Core Features Left
#
core-features-left:


  # Feature
  - name: Mechanical Engineering
    description: Automotive, Mechatronics, Fluids, Materials, Thermodynamics
    icon: pe-7s-rocket
 
  # Feature
  - name: Statistics
    description: Descriptive, Regression, Confidence Interval, Hypothesis testing, Chi-Squared Testing, ANOVA
    icon: pe-7s-note 
    
  # Feature
  - name: Machine and Deep Learning
    description: XGBoost, Random Forest, Neural Networks, Clustering, NLP, Image Classification, Object Detection
    icon: pe-7s-network
 
    # Feature
  - name: Structured Query Language (SQL)
    description: Queries, Database Management, Data Structure
    icon: pe-7s-server
   

#
# Core Features Right
#
core-features-right:
  
  # Feature
  - name: Computor Aided Design
    description: Versed in AutoCAD and Solidworks 3-D design and simulation work and technical drawings.
    icon: pe-7s-box2  
    
  # Feature
  - name: Visualization
    description: Tableau, Microsoft Office, and Adobe products
    icon: pe-7s-display2

  # Feature
  - name: Coding Languages <br> R and Python
    description: Pandas, NumPy, Seaborn, Matplotlib, Sklearn, whisper, keras, selenium, BeautifulSoup, Tidyverse, Xgboost, randomForest, caret, cluster, rvest
    icon: pe-7s-monitor

# #####################################
# ########### Testimonials ############
# #####################################
# testimonials-title: Testimonials
# testimonials-description: Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi.
# 
# #
# # Testimonials
# #
# testimonials:
#   # Client
#   - name: Johnatan Doe
#     url: http://themeforest.net
#     url-text: ThemeForest.net
#     avatar: avatar-01.jpg
#     cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
#     logo-img: themeforest.png
# 
#   # Client
#   - name: Adam Smith
#     url: http://codecanyon.net
#     url-text: CodeCanyon.net
#     avatar: avatar-02.jpg
#     cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
#     logo-img: codecanyon.png
# 
#   # Client
#   - name: Irene Warner
#     url: http://videohive.net
#     url-text: VideoHive.net
#     avatar: avatar-03.jpg
#     cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
#     logo-img: videohive.png
# 
#   # Client
#   - name: Richard Ryan
#     url: http://audiojungle.net
#     url-text: AudioJungle.net
#     avatar: avatar-04.jpg
#     cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
#     logo-img: audiojungle.png

#####################################
############# Our Blog ##############
#####################################
blog-title: Explore My Projects
blog-description: Explore some of my thoughts and comments on projects or interests!

#####################################
############### Team ################
#####################################
# team-title: About me
# team-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#
# Team Members
#
# team:
#   # Team Member
#   - name: Jacqueline Krohn
#     tagline: Business Analyst,  Mechanical Engineer
#     avatar: avatar-me.jpg
# 
#     # Social Links
#     youtube: "#"
#     pinterest: "#"
#     facebook: "#"
#     twitter: "#"
#     google-plus: "#"
#     vimeo: "#"

# #####################################
# ########## Pricing Tables ###########
# #####################################
# pricing-title: Pricing Tables
# pricing-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.
# 
# #
# # Plan Personal
# #
# plan-personal-price: $99
# plan-personal-offer-1-title: 01 PSD Pack
# plan-personal-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-personal-offer-2-title: 100 Support Tickets
# plan-personal-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-personal-url: "#"
# 
# #
# # Plan Business
# #
# plan-business-price: $499
# plan-business-offer-1-title: 05 PSD Pack
# plan-business-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-business-offer-2-title: 1000 Support Tickets
# plan-business-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-business-url: "#"
# 
# #
# # Plan Ultimate
# #
# plan-ultimate-price: $999
# plan-ultimate-offer-1-title: 10 PSD Pack
# plan-ultimate-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-ultimate-offer-2-title: Support Unlimited
# plan-ultimate-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-ultimate-url: "#"

#####################################
############   Contact   ############
#####################################
contact-title: Contact Me
contact-description: Send me an email to chat!

#####################################
#############   Footer   ############
#####################################
footer-description: Personal website for Jacqueline Krohn.
footer-copyright-text: Krohn
footer-copyright-url: https://github.com/jackie-krohn
footer-copyright-year: 2023
